### ISSUE TITLE
Support ui-route and components

### ISSUE THREAD

**Issue by Nkmol** [ionic-team/ionic-v1#236]
Is it possible to manually import a new version of `angular-ui-route`? 

I am following the best practices of AngularJS which encourage you to use the new Components. Everything works fine, expect States. Where I need at least v1.0.0: https://github.com/angular-ui/ui-router/issues/2627

How can I use this feature within ionic?

**Comment by Nkmol** [comment]
To use the component feature in combination with the older `angular-ui-route`, you can define the template and controller directly from the component in the state:

    import LoginComponent from './login.component';

    .component('login', LoginComponent)
    .config($stateProvider => {
        'ngInject';

        $stateProvider
            .state('login', {
                parent: 'app',
                url: '/login',
                template: LoginComponent.template,
                controller: LoginComponent.controller
            })
    })

This way you can still use the `component()` notation with the older routing library.

**Comment by Nkmol** [comment]
A way to still use `components` with a old version of `angular-ui-route`, is by just writing the component element as the template: `<picture />`

This way the Controller will be attached to your defined component.

However, this might break some ionic functionality, as ionic does not allow a non-ionic element to be in between them (for example with `<ion-nav-view />`).

To fix this, you can simply set the wrapper of your component to be your ionic container by tag: `<picture ion-view />`

**In total:**

_Written in ES6_

    .component('picture', PictureComponent)
    .config($stateProvider => {
        'ngInject';
        $stateProvider
            .state('app.picture', {
                url: '/picture',
                template: `
                    <picture ion-view />
                `
            })
    })

**Comment by gabn88** [comment]
Wow, this is exactly what I needed, thanks!

**Comment by Nkmol** [comment]
@gabn88 I do not remember having any problems with the other ionic elements using this structure. Maybe it has to do with something else beyond this component syntax?
