### ISSUE TITLE
ionic v1 fail to start with cli

### ISSUE THREAD

**Issue by sonicwong** [ionic-team/ionic-v1#266]
Ionic version: (check one with "x")
[x] 1.x (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] 2.x
[ ] 3.x

I'm submitting a ... (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

Current behavior:
stopped.

Expected behavior:
open browser and start app.

Steps to reproduce:
Just installed latest cli for ionic v1 and run 'ionic serve':
[INFO] Starting server: --port=8100 --p=8100 --livereload-port=35729 --r=35729 --address=0.0.0.0 - Ctrl+C to cancel
TypeError: Cannot read property 'emit' of undefined

Fix:
Manually change the "@ionic/cli-plugin-ionic1" to  "1.3.0" in package.json.

May be similar to this case?
https://github.com/ionic-team/ionic-cli/issues/2383

Ionic info:
```
global packages:
ionic/cli-utils : 1.3.0
Ionic CLI        : 3.3.0

local packages:
ionic/cli-plugin-ionic1 : 2.0.0
Ionic Framework          : ionic1 1.3.3

System:
Node       : v6.9.4
OS         : macOS Sierra
Xcode      : Xcode 8.3.2 Build version 8E2002 
ios-deploy : 1.9.0 
ios-sim    : 5.0.11
```

**Comment by gurubhandarkar** [comment]
Same error here. How to fix this ? i've change the version from "0.0.1" to "1.0.0" in package.json but not working.

global packages:

    @ionic/cli-utils : 1.0.0
    Cordova CLI      : 7.0.0 
    Ionic CLI        : 3.0.0

local packages:

    @ionic/cli-plugin-cordova : 1.4.0
    @ionic/cli-plugin-ionic1  : 2.0.0
    Cordova Platforms         : none
    Ionic Framework           : ionic1 1.3.3

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by sonicwong** [comment]
@gurubhandarkar
change cli-plugin-ionic1 from 3.0.0 to 1.3.0.

**Comment by gurubhandarkar** [comment]
Working. Thank you 👍

**Comment by sonicwong** [comment]
After update to latest ionic lib by: 'npm install -g ionic@latest'.
Error gone.
