### ISSUE TITLE
Ionic v1 now crashes (without code changing)

### ISSUE THREAD

**Issue by ben-pritchard** [ionic-team/ionic-v1#321]
I am developing an app that crashes soon after start up (sometimes immediately after logging in, sometimes after navigating to a couple pages first, one time before even logging in!). This occurs after entering the command `ionic build ios` and running the app through Xcode on my connected iPad and no errors are produced.

After lots of unfruitful troubleshooting, I checked to see if a previous app I had developed that is live and without bugs would still run without crashing (and I haven't made any code changes to it). So I ran `ionic build ios` and ran the app on my iPad through Xcode and it crashed after logging in and navigating to a page. Since that's the same code that is out in the wild and working correctly, the problem is probably not from the app code.

Any ideas? Could it have something to do with changes to Xcode? Even if I deploy my app to TestFlight, the app still crashes. Could it have something to do with dependencies or ionic CLI updates? I'm very confused about this!

**Comment by kensodemann** [comment]
Question:

> So I ran ionic build ios and ran the app on my iPad through Xcode and it crashed after logging in and navigating to a page.

What has changed on your system since the last successful run? Just XCode? Or did you also upgrade the CLI? What if you create a fresh v1 app from a starter? Does that work or does that fail?

**Comment by ben-pritchard** [comment]
I upgraded the CLI a few times but would that affect the way the app builds in Xcode and TestFlight? I don't know for sure if Xcode has been upgraded (I imagine some automatic updates).

I will try creating a fresh v1 app.

**Comment by ben-pritchard** [comment]
Ok, it turns out it's because my company's iPad we were using is way out of date and slow. But when I tried releasing the app in TestFlight, the app didn't crash in any of the phones we tried. Nor did it crash when running the app in the emulator by running `ionic cordova emulate ios --c`. Darn planned obsolescence, that iPad is only 3 years old!
